# TFC - iEquus - Raio-x

## Imports

In [ ]:
from utils import *

## Modelo inicial

In [ ]:
path = "treino_modelos"

In [ ]:
modelo_origem = pd.read_csv(f"{path}/resultados_modelos_iniciais.csv")
modelo_origem.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.436945,0.435897,0.461458,0.434375,95.0
resnet18,0.403668,0.410256,0.515104,0.406250,105.0
vgg11,0.400157,0.410256,0.458557,0.412500,87.0
googlenet,0.399669,0.397436,0.438542,0.400000,135.5
convnext_small,0.365334,0.371795,0.392857,0.371875,66.0
convnext_tiny,0.364651,0.371795,0.396478,0.375000,65.5
resnet50,0.363641,0.371795,0.422599,0.375000,27.5
vit,0.340341,0.333333,0.365179,0.328125,133.5
mobilenet_v3_small,0.335588,0.346154,0.367708,0.353125,45.0
nasnet_large,0.332046,0.320513,0.397978,0.325000,46.0
convnext_base,0.300855,0.307692,0.393136,0.306250,3.0
efficientnet_v2_s,0.291629,0.307692,0.345660,0.303125,34.0
se_resnext50,0.281624,0.320513,0.286438,0.315625,67.5
efficientnet_v2_m,0.267163,0.282051,0.292212,0.278125,97.5
densenet121,0.248160,0.256410,0.382887,0.256250,68.5

In [ ]:
modelo_origem.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.309848,0.307692,0.325000,0.30000,88
17,vit,0.370833,0.358974,0.405357,0.35625,179
21,vgg11,0.412463,0.435897,0.494048,0.43750,62
6,vgg11,0.387851,0.384615,0.423065,0.38750,112
13,se_resnext50,0.276091,0.307692,0.289394,0.30000,68
28,se_resnext50,0.287157,0.333333,0.283482,0.33125,67
16,resnet50,0.355880,0.358974,0.415179,0.36250,41
1,resnet50,0.371401,0.384615,0.430019,0.38750,14
0,resnet18,0.404657,0.410256,0.569792,0.40625,110
15,resnet18,0.402679,0.410256,0.460417,0.40625,100
29,nasnet_large,0.290783,0.282051,0.383456,0.28750,84
14,nasnet_large,0.373310,0.358974,0.412500,0.36250,8
18,mobilenet_v3_small,0.327816,0.333333,0.381250,0.34375,61
3,mobilenet_v3_small,0.343360,0.358974,0.354167,0.36250,29
4,googlenet,0.409091,0.410256,0.420833,0.40625,133
19,googlenet,0.390247,0.384615,0.456250,0.39375,138
25,efficientnet_v2_s,0.296795,0.307692,0.320833,0.30625,9
10,efficientnet_v2_s,0.286462,0.307692,0.370486,0.30000,59
11,efficientnet_v2_m,0.277381,0.282051,0.310119,0.27500,54
26,efficientnet_v2_m,0.256944,0.282051,0.274306,0.28125,141
5,dino_vit,0.430997,0.435897,0.435417,0.43125,97
20,dino_vit,0.442893,0.435897,0.487500,0.43750,93
27,densenet121,0.228947,0.230769,0.403274,0.23125,90
12,densenet121,0.267373,0.282051,0.362500,0.28125,47
7,convnext_tiny,0.325595,0.333333,0.371429,0.33750,55
22,convnext_tiny,0.403707,0.410256,0.421528,0.41250,76
8,convnext_small,0.382572,0.384615,0.421131,0.38750,107
23,convnext_small,0.348096,0.358974,0.364583,0.35625,25
24,convnext_base,0.275595,0.282051,0.331944,0.28125,4
9,convnext_base,0.326115,0.333333,0.454327,0.33125,2

## Data augmentation

### RandomRotation(10)

In [ ]:
augmentation1 = pd.read_csv(f"{path}/resultados_data_augmentation1.csv")
augmentation1.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.464242,0.474359,0.484375,0.468750,107.0
vit,0.427336,0.423077,0.451935,0.418750,111.5
vgg11,0.379626,0.384615,0.429167,0.381250,66.5
efficientnet_v2_m,0.365111,0.358974,0.439908,0.356250,98.0
se_resnext50,0.332116,0.371795,0.371438,0.371875,41.0
resnet50,0.327260,0.346154,0.401538,0.340625,69.5
efficientnet_v2_s,0.313394,0.333333,0.310640,0.337500,42.0
convnext_tiny,0.309939,0.320513,0.396487,0.318750,56.5
convnext_small,0.307724,0.333333,0.328819,0.328125,53.0
convnext_base,0.291131,0.320513,0.310764,0.315625,140.0
mobilenet_v3_small,0.289812,0.320513,0.283259,0.325000,77.0
nasnet_large,0.283659,0.294872,0.376414,0.296875,34.0
googlenet,0.276814,0.320513,0.344844,0.312500,64.0
resnet18,0.276196,0.307692,0.288100,0.309375,132.0
densenet121,0.224679,0.243590,0.257512,0.243750,59.0

In [ ]:
augmentation1.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.438005,0.435897,0.465179,0.43125,52
17,vit,0.416667,0.410256,0.438690,0.40625,171
21,vgg11,0.382326,0.384615,0.429018,0.38125,53
6,vgg11,0.376926,0.384615,0.429315,0.38125,80
13,se_resnext50,0.330898,0.358974,0.343254,0.36250,37
28,se_resnext50,0.333333,0.384615,0.399621,0.38125,45
16,resnet50,0.315873,0.333333,0.450694,0.32500,120
1,resnet50,0.338647,0.358974,0.352381,0.35625,19
0,resnet18,0.267968,0.282051,0.286616,0.28125,131
15,resnet18,0.284425,0.333333,0.289583,0.33750,133
29,nasnet_large,0.278510,0.282051,0.446875,0.28125,54
14,nasnet_large,0.288808,0.307692,0.305952,0.31250,14
18,mobilenet_v3_small,0.274496,0.307692,0.270982,0.31250,83
3,mobilenet_v3_small,0.305128,0.333333,0.295536,0.33750,71
4,googlenet,0.277778,0.307692,0.355392,0.30000,96
19,googlenet,0.275850,0.333333,0.334295,0.32500,32
25,efficientnet_v2_s,0.336889,0.358974,0.336161,0.36875,36
10,efficientnet_v2_s,0.289899,0.307692,0.285119,0.30625,48
11,efficientnet_v2_m,0.345265,0.333333,0.448864,0.33125,121
26,efficientnet_v2_m,0.384957,0.384615,0.430952,0.38125,75
5,dino_vit,0.468635,0.487179,0.475000,0.48125,86
20,dino_vit,0.459848,0.461538,0.493750,0.45625,128
27,densenet121,0.203526,0.230769,0.208963,0.23125,78
12,densenet121,0.245833,0.256410,0.306061,0.25625,40
7,convnext_tiny,0.294246,0.307692,0.384343,0.30625,30
22,convnext_tiny,0.325631,0.333333,0.408631,0.33125,83
8,convnext_small,0.294048,0.307692,0.320833,0.30000,97
23,convnext_small,0.321399,0.358974,0.336806,0.35625,9
24,convnext_base,0.268353,0.307692,0.277778,0.30000,123
9,convnext_base,0.313909,0.333333,0.343750,0.33125,157

### ColorJitter

In [ ]:
augmentation2 = pd.read_csv(f"{path}/resultados_data_augmentation2.csv")
augmentation2.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.436706,0.435897,0.462723,0.431250,99.0
convnext_tiny,0.408354,0.423077,0.420536,0.421875,30.0
googlenet,0.406088,0.410256,0.483545,0.415625,143.5
resnet18,0.400991,0.423077,0.496834,0.418750,60.0
vgg11,0.395572,0.410256,0.463542,0.409375,82.5
mobilenet_v3_small,0.379771,0.384615,0.433408,0.387500,41.5
resnet50,0.367623,0.371795,0.470245,0.368750,131.0
convnext_small,0.352505,0.333333,0.417903,0.334375,32.0
vit,0.336963,0.333333,0.359673,0.331250,97.0
efficientnet_v2_m,0.321007,0.346154,0.334159,0.337500,85.0
convnext_base,0.296857,0.358974,0.298723,0.350000,9.5
se_resnext50,0.296340,0.307692,0.350805,0.306250,53.5
nasnet_large,0.295685,0.307692,0.355114,0.309375,162.0
efficientnet_v2_s,0.225084,0.243590,0.265675,0.237500,49.5
densenet121,0.223333,0.256410,0.257102,0.256250,60.5

In [ ]:
augmentation2.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.356250,0.358974,0.374405,0.35625,68
17,vit,0.317677,0.307692,0.344940,0.30625,126
21,vgg11,0.379293,0.384615,0.422917,0.38125,60
6,vgg11,0.411851,0.435897,0.504167,0.43750,105
13,se_resnext50,0.295405,0.307692,0.319508,0.30625,38
28,se_resnext50,0.297276,0.307692,0.382102,0.30625,69
16,resnet50,0.356498,0.358974,0.397781,0.35625,150
1,resnet50,0.378749,0.384615,0.542708,0.38125,112
0,resnet18,0.405005,0.435897,0.549621,0.43125,47
15,resnet18,0.396977,0.410256,0.444048,0.40625,73
29,nasnet_large,0.288393,0.282051,0.318561,0.28750,135
14,nasnet_large,0.302976,0.333333,0.391667,0.33125,189
18,mobilenet_v3_small,0.359174,0.358974,0.392262,0.36250,47
3,mobilenet_v3_small,0.400369,0.410256,0.474554,0.41250,36
4,googlenet,0.416953,0.435897,0.524382,0.44375,142
19,googlenet,0.395223,0.384615,0.442708,0.38750,145
25,efficientnet_v2_s,0.193620,0.230769,0.175992,0.22500,85
10,efficientnet_v2_s,0.256548,0.256410,0.355357,0.25000,14
11,efficientnet_v2_m,0.311806,0.333333,0.328571,0.32500,127
26,efficientnet_v2_m,0.330208,0.358974,0.339746,0.35000,43
5,dino_vit,0.442730,0.435897,0.484375,0.43125,82
20,dino_vit,0.430682,0.435897,0.441071,0.43125,116
27,densenet121,0.191239,0.230769,0.245833,0.23125,37
12,densenet121,0.255426,0.282051,0.268371,0.28125,84
7,convnext_tiny,0.429004,0.435897,0.466071,0.43125,12
22,convnext_tiny,0.387704,0.410256,0.375000,0.41250,48
8,convnext_small,0.349603,0.333333,0.405357,0.33750,47
23,convnext_small,0.355408,0.333333,0.430449,0.33125,17
24,convnext_base,0.300411,0.358974,0.277778,0.35000,14
9,convnext_base,0.293304,0.358974,0.319668,0.35000,5

### RandomResizedCrop

In [ ]:
augmentation3 = pd.read_csv(f"{path}/resultados_data_augmentation3.csv")
augmentation3.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.471392,0.474359,0.495536,0.468750,55.0
resnet18,0.384664,0.397436,0.459524,0.403125,61.5
resnet50,0.382047,0.397436,0.484512,0.387500,73.5
vgg11,0.381967,0.397436,0.392911,0.393750,70.5
convnext_tiny,0.351937,0.358974,0.377951,0.365625,70.0
se_resnext50,0.340345,0.358974,0.363479,0.353125,70.5
efficientnet_v2_m,0.335033,0.346154,0.372173,0.337500,99.0
densenet121,0.319311,0.333333,0.362843,0.331250,31.0
convnext_base,0.302264,0.320513,0.309276,0.315625,32.0
vit,0.302217,0.320513,0.309821,0.312500,41.5
convnext_small,0.289537,0.294872,0.376786,0.293750,58.5
googlenet,0.277697,0.294872,0.312184,0.287500,102.5
nasnet_large,0.265710,0.294872,0.318556,0.290625,38.5
mobilenet_v3_small,0.254721,0.269231,0.250298,0.271875,60.5
efficientnet_v2_s,0.250254,0.243590,0.321733,0.246875,79.0

In [ ]:
augmentation3.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.322917,0.333333,0.347321,0.32500,49
17,vit,0.281517,0.307692,0.272321,0.30000,34
21,vgg11,0.387942,0.410256,0.383929,0.40625,54
6,vgg11,0.375992,0.384615,0.401894,0.38125,87
13,se_resnext50,0.334098,0.358974,0.350063,0.35625,95
28,se_resnext50,0.346591,0.358974,0.376894,0.35000,46
16,resnet50,0.388447,0.410256,0.478846,0.40000,115
1,resnet50,0.375647,0.384615,0.490179,0.37500,32
0,resnet18,0.386204,0.410256,0.417262,0.41875,56
15,resnet18,0.383124,0.384615,0.501786,0.38750,67
29,nasnet_large,0.252110,0.282051,0.246338,0.28125,6
14,nasnet_large,0.279310,0.307692,0.390774,0.30000,71
18,mobilenet_v3_small,0.260516,0.282051,0.256548,0.28125,69
3,mobilenet_v3_small,0.248927,0.256410,0.244048,0.26250,52
4,googlenet,0.269255,0.282051,0.309028,0.27500,117
19,googlenet,0.286139,0.307692,0.315341,0.30000,88
25,efficientnet_v2_s,0.253423,0.256410,0.304924,0.25625,101
10,efficientnet_v2_s,0.247086,0.230769,0.338542,0.23750,57
11,efficientnet_v2_m,0.346605,0.358974,0.362798,0.35000,77
26,efficientnet_v2_m,0.323460,0.333333,0.381548,0.32500,121
5,dino_vit,0.486237,0.487179,0.527083,0.48125,44
20,dino_vit,0.456548,0.461538,0.463988,0.45625,66
27,densenet121,0.314952,0.333333,0.386905,0.33125,28
12,densenet121,0.323671,0.333333,0.338782,0.33125,34
7,convnext_tiny,0.358270,0.358974,0.380208,0.36875,47
22,convnext_tiny,0.345604,0.358974,0.375694,0.36250,93
8,convnext_small,0.287408,0.307692,0.374107,0.30625,98
23,convnext_small,0.291667,0.282051,0.379464,0.28125,19
24,convnext_base,0.291531,0.307692,0.302579,0.30000,25
9,convnext_base,0.312996,0.333333,0.315972,0.33125,39

### RandomHorizontalFlip

In [ ]:
augmentation4 = pd.read_csv(f"{path}/resultados_data_augmentation4.csv")
augmentation4.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
googlenet,0.380916,0.397436,0.393700,0.387500,120.0
resnet18,0.378274,0.384615,0.509240,0.381250,104.5
vgg11,0.362516,0.371795,0.426910,0.368750,34.0
convnext_tiny,0.350812,0.371795,0.350645,0.371875,77.0
dino_vit,0.338093,0.358974,0.341344,0.359375,84.0
vit,0.337204,0.320513,0.379715,0.318750,46.0
nasnet_large,0.330510,0.294872,0.414757,0.300000,188.0
efficientnet_v2_m,0.325271,0.333333,0.370387,0.334375,61.0
mobilenet_v3_small,0.318998,0.346154,0.354836,0.350000,18.0
resnet50,0.302937,0.307692,0.335789,0.306250,125.0
se_resnext50,0.298662,0.294872,0.321503,0.287500,39.0
efficientnet_v2_s,0.297605,0.307692,0.312128,0.312500,102.0
convnext_small,0.289696,0.294872,0.346230,0.290625,19.5
densenet121,0.258958,0.282051,0.311161,0.281250,47.5
convnext_base,0.255247,0.320513,0.240016,0.312500,28.0

In [ ]:
augmentation4.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.326491,0.307692,0.375149,0.30625,75
17,vit,0.347917,0.333333,0.384280,0.33125,17
21,vgg11,0.369156,0.358974,0.423611,0.35625,37
6,vgg11,0.355876,0.384615,0.430208,0.38125,31
13,se_resnext50,0.279963,0.282051,0.296875,0.27500,46
28,se_resnext50,0.317361,0.307692,0.346131,0.30000,32
16,resnet50,0.293290,0.307692,0.318452,0.30000,80
1,resnet50,0.312584,0.307692,0.353125,0.31250,170
0,resnet18,0.383631,0.384615,0.564015,0.38125,119
15,resnet18,0.372917,0.384615,0.454464,0.38125,90
29,nasnet_large,0.327291,0.282051,0.420139,0.28750,186
14,nasnet_large,0.333730,0.307692,0.409375,0.31250,190
18,mobilenet_v3_small,0.338104,0.358974,0.414881,0.36875,13
3,mobilenet_v3_small,0.299893,0.333333,0.294792,0.33125,23
4,googlenet,0.354067,0.358974,0.386806,0.35000,150
19,googlenet,0.407765,0.435897,0.400595,0.42500,90
25,efficientnet_v2_s,0.309015,0.333333,0.312500,0.33750,103
10,efficientnet_v2_s,0.286195,0.282051,0.311756,0.28750,101
11,efficientnet_v2_m,0.338041,0.358974,0.327083,0.36250,57
26,efficientnet_v2_m,0.312500,0.307692,0.413690,0.30625,65
5,dino_vit,0.334694,0.358974,0.327530,0.35625,67
20,dino_vit,0.341492,0.358974,0.355159,0.36250,101
27,densenet121,0.255842,0.282051,0.268750,0.28125,59
12,densenet121,0.262073,0.282051,0.353571,0.28125,36
7,convnext_tiny,0.346465,0.358974,0.352083,0.35625,67
22,convnext_tiny,0.355159,0.384615,0.349206,0.38750,87
8,convnext_small,0.254960,0.256410,0.286210,0.25000,19
23,convnext_small,0.324432,0.333333,0.406250,0.33125,20
24,convnext_base,0.243590,0.307692,0.208929,0.30000,39
9,convnext_base,0.266904,0.333333,0.271104,0.32500,17

### RandomAffine

In [ ]:
augmentation5 = pd.read_csv(f"{path}/resultados_data_augmentation5.csv")
augmentation5.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.487477,0.512821,0.491716,0.506250,88.0
vit,0.399911,0.397436,0.464807,0.393750,72.5
vgg11,0.385730,0.397436,0.418775,0.393750,84.5
efficientnet_v2_m,0.377264,0.384615,0.485227,0.384375,73.0
convnext_small,0.361723,0.371795,0.387500,0.375000,56.0
resnet50,0.354613,0.384615,0.396532,0.381250,97.5
convnext_tiny,0.349826,0.346154,0.397644,0.346875,11.0
resnet18,0.329202,0.358974,0.350710,0.371875,84.5
efficientnet_v2_s,0.321533,0.333333,0.332614,0.334375,87.0
mobilenet_v3_small,0.307521,0.346154,0.312624,0.350000,72.0
nasnet_large,0.301686,0.320513,0.301116,0.325000,132.5
convnext_base,0.285801,0.320513,0.283917,0.315625,75.0
se_resnext50,0.282943,0.307692,0.345766,0.309375,90.5
googlenet,0.257670,0.307692,0.327033,0.312500,64.0
densenet121,0.237206,0.256410,0.298958,0.253125,33.5

In [ ]:
augmentation5.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.404870,0.410256,0.482738,0.40625,47
17,vit,0.394952,0.384615,0.446875,0.38125,98
21,vgg11,0.422430,0.435897,0.451786,0.43125,83
6,vgg11,0.349031,0.358974,0.385764,0.35625,86
13,se_resnext50,0.270530,0.307692,0.372024,0.30625,21
28,se_resnext50,0.295356,0.307692,0.319508,0.31250,160
16,resnet50,0.310317,0.333333,0.342370,0.33750,56
1,resnet50,0.398909,0.435897,0.450694,0.42500,139
0,resnet18,0.324278,0.358974,0.346496,0.37500,115
15,resnet18,0.334127,0.358974,0.354924,0.36875,54
29,nasnet_large,0.307044,0.307692,0.329167,0.31875,115
14,nasnet_large,0.296329,0.333333,0.273065,0.33125,150
18,mobilenet_v3_small,0.323284,0.358974,0.321429,0.36250,67
3,mobilenet_v3_small,0.291758,0.333333,0.303819,0.33750,77
4,googlenet,0.259028,0.307692,0.319508,0.31875,83
19,googlenet,0.256313,0.307692,0.334559,0.30625,45
25,efficientnet_v2_s,0.319192,0.333333,0.308631,0.33750,113
10,efficientnet_v2_s,0.323875,0.333333,0.356597,0.33125,61
11,efficientnet_v2_m,0.341712,0.358974,0.502083,0.35625,90
26,efficientnet_v2_m,0.412816,0.410256,0.468371,0.41250,56
5,dino_vit,0.477976,0.512821,0.469544,0.50625,119
20,dino_vit,0.496979,0.512821,0.513889,0.50625,57
27,densenet121,0.231944,0.230769,0.264583,0.23125,37
12,densenet121,0.242468,0.282051,0.333333,0.27500,30
7,convnext_tiny,0.336039,0.333333,0.417163,0.33125,16
22,convnext_tiny,0.363612,0.358974,0.378125,0.36250,6
8,convnext_small,0.361910,0.384615,0.383929,0.38750,86
23,convnext_small,0.361535,0.358974,0.391071,0.36250,26
24,convnext_base,0.262637,0.307692,0.268429,0.30625,140
9,convnext_base,0.308965,0.333333,0.299405,0.32500,10

### AutoAugment

In [ ]:
augmentation6 = pd.read_csv(f"{path}/resultados_data_augmentation6.csv")
augmentation6.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.469296,0.474359,0.492708,0.468750,93.5
resnet18,0.427841,0.448718,0.541555,0.446875,97.5
vgg11,0.423222,0.423077,0.484673,0.421875,104.5
vit,0.399702,0.410256,0.411979,0.406250,156.5
convnext_tiny,0.385433,0.397436,0.420610,0.393750,69.0
googlenet,0.363465,0.371795,0.451786,0.368750,96.5
convnext_small,0.341909,0.371795,0.391022,0.368750,38.5
resnet50,0.341041,0.333333,0.406324,0.331250,125.5
nasnet_large,0.335035,0.320513,0.408507,0.321875,150.5
se_resnext50,0.330979,0.358974,0.381834,0.350000,92.0
mobilenet_v3_small,0.325751,0.358974,0.347594,0.356250,46.0
densenet121,0.307904,0.333333,0.331399,0.331250,54.0
efficientnet_v2_s,0.301068,0.333333,0.330952,0.328125,48.0
convnext_base,0.297669,0.320513,0.313856,0.315625,111.0
efficientnet_v2_m,0.255259,0.307692,0.258829,0.300000,110.0

In [ ]:
augmentation6.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.403517,0.410256,0.411905,0.40625,147
17,vit,0.395887,0.410256,0.412054,0.40625,166
21,vgg11,0.412843,0.410256,0.460714,0.40625,97
6,vgg11,0.433600,0.435897,0.508631,0.43750,112
13,se_resnext50,0.320833,0.358974,0.309821,0.35000,97
28,se_resnext50,0.341126,0.358974,0.453846,0.35000,87
16,resnet50,0.307485,0.307692,0.415774,0.30000,74
1,resnet50,0.374597,0.358974,0.396875,0.36250,177
0,resnet18,0.450126,0.461538,0.580729,0.46250,74
15,resnet18,0.405556,0.435897,0.502381,0.43125,121
29,nasnet_large,0.352895,0.333333,0.451389,0.33750,161
14,nasnet_large,0.317174,0.307692,0.365625,0.30625,140
18,mobilenet_v3_small,0.271073,0.307692,0.262153,0.30625,25
3,mobilenet_v3_small,0.380429,0.410256,0.433036,0.40625,67
4,googlenet,0.386706,0.410256,0.497917,0.40625,104
19,googlenet,0.340224,0.333333,0.405655,0.33125,89
25,efficientnet_v2_s,0.274989,0.307692,0.350000,0.30625,21
10,efficientnet_v2_s,0.327146,0.358974,0.311905,0.35000,75
11,efficientnet_v2_m,0.248434,0.307692,0.244444,0.30000,138
26,efficientnet_v2_m,0.262083,0.307692,0.273214,0.30000,82
5,dino_vit,0.459821,0.461538,0.479167,0.45625,86
20,dino_vit,0.478770,0.487179,0.506250,0.48125,101
27,densenet121,0.269559,0.307692,0.292560,0.30625,73
12,densenet121,0.346248,0.358974,0.370238,0.35625,35
7,convnext_tiny,0.391293,0.410256,0.414137,0.40625,65
22,convnext_tiny,0.379573,0.384615,0.427083,0.38125,73
8,convnext_small,0.330139,0.358974,0.358631,0.35625,41
23,convnext_small,0.353680,0.384615,0.423413,0.38125,36
24,convnext_base,0.304167,0.333333,0.301076,0.33125,108
9,convnext_base,0.291171,0.307692,0.326637,0.30000,114

### Augmentation Final 1

In [ ]:
augmentation_final1 = pd.read_csv(f"aug_f1/resultados_data_augmentation_final1.csv")
augmentation_final1.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.425237,0.435897,0.484512,0.431250,86.0
convnext_tiny,0.375027,0.384615,0.376141,0.384375,51.5
efficientnet_v2_m,0.368267,0.397436,0.419841,0.387500,135.0
convnext_small,0.352878,0.371795,0.407589,0.368750,61.0
googlenet,0.337451,0.358974,0.450620,0.356250,140.5
resnet18,0.331559,0.358974,0.369623,0.368750,80.0
mobilenet_v3_small,0.324148,0.358974,0.319841,0.350000,57.0
efficientnet_v2_s,0.320892,0.307692,0.473264,0.306250,87.0
vit,0.314795,0.333333,0.396949,0.328125,37.5
resnet50,0.311072,0.358974,0.361298,0.350000,107.5
vgg11,0.303242,0.307692,0.383333,0.303125,75.0
se_resnext50,0.298291,0.333333,0.332624,0.325000,118.5
nasnet_large,0.289128,0.307692,0.294494,0.300000,94.5
convnext_base,0.284344,0.307692,0.331277,0.300000,143.0
densenet121,0.223975,0.269231,0.244801,0.262500,44.5

In [ ]:
augmentation_final1.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.317541,0.358974,0.387153,0.35625,46
17,vit,0.312049,0.307692,0.406746,0.30000,29
21,vgg11,0.313303,0.307692,0.401488,0.30625,57
6,vgg11,0.293182,0.307692,0.365179,0.30000,93
13,se_resnext50,0.310157,0.358974,0.342628,0.35000,112
28,se_resnext50,0.286425,0.307692,0.322619,0.30000,125
16,resnet50,0.309452,0.358974,0.391346,0.35000,52
1,resnet50,0.312693,0.358974,0.331250,0.35000,163
0,resnet18,0.375992,0.410256,0.372768,0.41875,72
15,resnet18,0.287126,0.307692,0.366477,0.31875,88
29,nasnet_large,0.278003,0.307692,0.282738,0.30000,162
14,nasnet_large,0.300253,0.307692,0.306250,0.30000,27
18,mobilenet_v3_small,0.340260,0.358974,0.350000,0.35000,35
3,mobilenet_v3_small,0.308036,0.358974,0.289683,0.35000,79
4,googlenet,0.354563,0.384615,0.440972,0.38125,149
19,googlenet,0.320338,0.333333,0.460268,0.33125,132
25,efficientnet_v2_s,0.333756,0.333333,0.529861,0.33125,113
10,efficientnet_v2_s,0.308029,0.282051,0.416667,0.28125,61
11,efficientnet_v2_m,0.350198,0.384615,0.381349,0.37500,135
26,efficientnet_v2_m,0.386337,0.410256,0.458333,0.40000,135
5,dino_vit,0.458471,0.461538,0.511012,0.45625,72
20,dino_vit,0.392002,0.410256,0.458013,0.40625,100
27,densenet121,0.241538,0.282051,0.291552,0.27500,7
12,densenet121,0.206412,0.256410,0.198050,0.25000,82
7,convnext_tiny,0.375812,0.384615,0.376984,0.38750,49
22,convnext_tiny,0.374242,0.384615,0.375298,0.38125,54
8,convnext_small,0.376923,0.410256,0.446429,0.40625,6
23,convnext_small,0.328833,0.333333,0.368750,0.33125,116
24,convnext_base,0.301804,0.333333,0.361012,0.32500,142
9,convnext_base,0.266884,0.282051,0.301542,0.27500,144

### Augmentation Final 2

In [ ]:
augmentation_final2 = pd.read_csv(f"aug_f2/resultados_data_augmentation_final2.csv")
augmentation_final2.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.428775,0.448718,0.544769,0.443750,95.0
efficientnet_v2_m,0.378750,0.371795,0.546007,0.368750,107.0
vgg11,0.342936,0.371795,0.369469,0.368750,107.5
vit,0.341189,0.346154,0.380556,0.340625,58.5
convnext_tiny,0.340080,0.346154,0.414211,0.350000,74.0
mobilenet_v3_small,0.337444,0.384615,0.361657,0.381250,52.5
se_resnext50,0.320524,0.346154,0.378869,0.350000,62.0
efficientnet_v2_s,0.302751,0.320513,0.352841,0.321875,91.0
resnet18,0.301557,0.333333,0.319246,0.340625,47.5
convnext_base,0.292889,0.320513,0.304613,0.315625,97.0
nasnet_large,0.283401,0.294872,0.311269,0.290625,132.5
googlenet,0.283005,0.294872,0.359876,0.300000,97.5
convnext_small,0.282620,0.307692,0.322917,0.300000,63.5
resnet50,0.268844,0.320513,0.288170,0.312500,147.0
densenet121,0.223623,0.269231,0.280952,0.262500,66.5

In [ ]:
augmentation_final2.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.335444,0.358974,0.350099,0.35000,42
17,vit,0.346934,0.333333,0.411012,0.33125,75
21,vgg11,0.332166,0.358974,0.362054,0.35625,98
6,vgg11,0.353707,0.384615,0.376885,0.38125,117
13,se_resnext50,0.361188,0.384615,0.451488,0.39375,42
28,se_resnext50,0.279861,0.307692,0.306250,0.30625,82
16,resnet50,0.279383,0.333333,0.320833,0.32500,140
1,resnet50,0.258306,0.307692,0.255506,0.30000,154
0,resnet18,0.316241,0.333333,0.352381,0.34375,29
15,resnet18,0.286874,0.333333,0.286111,0.33750,66
29,nasnet_large,0.310764,0.333333,0.315341,0.32500,176
14,nasnet_large,0.256039,0.256410,0.307197,0.25625,89
18,mobilenet_v3_small,0.333036,0.384615,0.314683,0.37500,46
3,mobilenet_v3_small,0.341853,0.384615,0.408631,0.38750,59
4,googlenet,0.280296,0.282051,0.392857,0.28750,61
19,googlenet,0.285714,0.307692,0.326894,0.31250,134
25,efficientnet_v2_s,0.293083,0.307692,0.300000,0.31250,104
10,efficientnet_v2_s,0.312419,0.333333,0.405682,0.33125,78
11,efficientnet_v2_m,0.346417,0.333333,0.538194,0.33125,102
26,efficientnet_v2_m,0.411083,0.410256,0.553819,0.40625,112
5,dino_vit,0.472457,0.487179,0.591941,0.48125,81
20,dino_vit,0.385094,0.410256,0.497596,0.40625,109
27,densenet121,0.255816,0.307692,0.286111,0.30000,76
12,densenet121,0.191430,0.230769,0.275794,0.22500,57
7,convnext_tiny,0.349604,0.358974,0.423958,0.36250,60
22,convnext_tiny,0.330556,0.333333,0.404464,0.33750,88
8,convnext_small,0.269765,0.307692,0.264137,0.30000,28
23,convnext_small,0.295475,0.307692,0.381696,0.30000,99
24,convnext_base,0.311205,0.333333,0.345833,0.33125,36
9,convnext_base,0.274573,0.307692,0.263393,0.30000,158

### Augmentation Final 3

In [ ]:
augmentation_final3 = pd.read_csv(f"aug_f3/resultados_data_augmentation_final3.csv")
augmentation_final3.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.487329,0.500000,0.517113,0.493750,84.0
resnet18,0.450958,0.461538,0.552827,0.465625,97.0
vit,0.376429,0.371795,0.430878,0.368750,49.5
efficientnet_v2_s,0.370517,0.358974,0.409797,0.362500,91.5
vgg11,0.369381,0.358974,0.485897,0.356250,93.0
resnet50,0.349710,0.358974,0.411458,0.356250,149.5
convnext_tiny,0.341538,0.371795,0.354248,0.362500,31.5
convnext_small,0.339931,0.358974,0.354924,0.350000,76.0
nasnet_large,0.319542,0.333333,0.341667,0.331250,67.0
mobilenet_v3_small,0.314502,0.333333,0.394792,0.331250,84.0
se_resnext50,0.312859,0.346154,0.419929,0.337500,39.5
convnext_base,0.293651,0.307692,0.335714,0.300000,10.0
densenet121,0.290862,0.346154,0.384799,0.340625,69.5
googlenet,0.285181,0.307692,0.314137,0.300000,127.0
efficientnet_v2_m,0.276522,0.307692,0.362216,0.300000,35.0

In [ ]:
augmentation_final3.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.392838,0.384615,0.451042,0.38125,60
17,vit,0.360020,0.358974,0.410714,0.35625,39
6,vgg11,0.369381,0.358974,0.485897,0.35625,93
22,se_resnext50,0.310471,0.333333,0.376984,0.32500,58
13,se_resnext50,0.315247,0.358974,0.462874,0.35000,21
1,resnet50,0.372962,0.384615,0.391667,0.38125,138
16,resnet50,0.326459,0.333333,0.431250,0.33125,161
15,resnet18,0.447238,0.461538,0.535714,0.46250,133
0,resnet18,0.454678,0.461538,0.569940,0.46875,61
14,nasnet_large,0.319542,0.333333,0.341667,0.33125,67
3,mobilenet_v3_small,0.314502,0.333333,0.394792,0.33125,84
4,googlenet,0.285181,0.307692,0.314137,0.30000,127
10,efficientnet_v2_s,0.371987,0.358974,0.427232,0.36250,63
20,efficientnet_v2_s,0.369048,0.358974,0.392361,0.36250,120
11,efficientnet_v2_m,0.276522,0.307692,0.362216,0.30000,35
5,dino_vit,0.472944,0.487179,0.492560,0.48125,94
18,dino_vit,0.501714,0.512821,0.541667,0.50625,74
12,densenet121,0.288420,0.333333,0.360507,0.33125,76
21,densenet121,0.293304,0.358974,0.409091,0.35000,63
7,convnext_tiny,0.358617,0.410256,0.339746,0.40000,36
19,convnext_tiny,0.324459,0.333333,0.368750,0.32500,27
8,convnext_small,0.339931,0.358974,0.354924,0.35000,76
9,convnext_base,0.293651,0.307692,0.335714,0.30000,10

### Augmentation Final 4

In [ ]:
augmentation_final4 = pd.read_csv(f"aug_f4/resultados_data_augmentation_final4.csv")
augmentation_final4.groupby("nome").mean().sort_values(by="f1_macro", ascending=False)

,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
nome,,,,,
dino_vit,0.445576,0.461538,0.529694,0.456250,73.5
mobilenet_v3_small,0.389320,0.410256,0.417535,0.412500,71.0
vit,0.373323,0.358974,0.441815,0.356250,86.5
vgg11,0.331093,0.384615,0.314931,0.381250,115.0
convnext_tiny,0.325298,0.333333,0.356944,0.331250,12.0
efficientnet_v2_m,0.319909,0.358974,0.392262,0.353125,60.0
efficientnet_v2_s,0.309876,0.320513,0.331052,0.321875,6.5
se_resnext50,0.304744,0.333333,0.330580,0.331250,82.0
resnet50,0.302350,0.358974,0.359890,0.350000,161.0
googlenet,0.293750,0.307692,0.368615,0.318750,65.0
resnet18,0.290190,0.307692,0.341518,0.306250,130.0
convnext_small,0.286932,0.307692,0.354167,0.300000,68.0
nasnet_large,0.284206,0.307692,0.293750,0.300000,85.0
convnext_base,0.271429,0.282051,0.313005,0.275000,101.0
densenet121,0.236198,0.256410,0.317708,0.250000,17.0

In [ ]:
augmentation_final4.sort_values(by=["nome"], ascending=False)

,nome,f1_macro,accuracy,precision_macro,recall_macro,best_epoch
2,vit,0.369453,0.358974,0.447024,0.35625,63
15,vit,0.377192,0.358974,0.436607,0.35625,110
6,vgg11,0.331093,0.384615,0.314931,0.38125,115
20,se_resnext50,0.281755,0.307692,0.291964,0.30625,36
13,se_resnext50,0.327732,0.358974,0.369196,0.35625,128
1,resnet50,0.302350,0.358974,0.359890,0.35000,161
0,resnet18,0.290190,0.307692,0.341518,0.30625,130
14,nasnet_large,0.284206,0.307692,0.293750,0.30000,85
3,mobilenet_v3_small,0.391865,0.410256,0.421230,0.41250,64
16,mobilenet_v3_small,0.386774,0.410256,0.413839,0.41250,78
4,googlenet,0.293750,0.307692,0.368615,0.31875,65
18,efficientnet_v2_s,0.318362,0.333333,0.341270,0.33125,12
10,efficientnet_v2_s,0.301389,0.307692,0.320833,0.31250,1
11,efficientnet_v2_m,0.336030,0.358974,0.504464,0.35625,42
19,efficientnet_v2_m,0.303788,0.358974,0.280060,0.35000,78
5,dino_vit,0.462477,0.487179,0.537798,0.48125,80
17,dino_vit,0.428675,0.435897,0.521591,0.43125,67
12,densenet121,0.236198,0.256410,0.317708,0.25000,17
7,convnext_tiny,0.325298,0.333333,0.356944,0.33125,12
8,convnext_small,0.286932,0.307692,0.354167,0.30000,68
9,convnext_base,0.271429,0.282051,0.313005,0.27500,101